# Generated by Django 5.2.4 on 2025-08-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin - Tam yetki'), ('manager', 'Yönetici - Ürün ve kategori yönetimi'), ('user', 'Kullanıcı - Sadece görüntüleme')], default='user', help_text='Kullanıcının sistem içindeki yetkilerini belirler', max_length=20, verbose_name='Kullanıcı Rolü'),
        ),
    ]
